# Generated by Django 5.0.2 on 2024-04-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employer_registrations', to='backend.user'),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='backend.user'),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='qualifications',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_registrations', to='backend.user'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='backend.user'),
        ),
        migrations.AlterModelTable(
            name='employerregistration',
            table='backend_employerregistration',
        ),
        migrations.AlterModelTable(
            name='job',
            table='backend_job',
        ),
        migrations.AlterModelTable(
            name='professional',
            table='backend_professional',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='backend_staff',
        ),
        migrations.AlterModelTable(
            name='user',
            table='backend_user',
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='backend.user')),
            ],
            options={
                'db_table': 'backend_employer',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='backend.employer'),
        ),
    ]
