# Generated by Django 5.0.2 on 2024-04-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_employerregistration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
    ]
