# Generated by Django 5.0.2 on 2024-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_professional_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
