# Generated by Django 5.0.2 on 2024-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
