# Generated by Django 5.0.4 on 2024-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_month_complete_professionalregistration_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalregistration',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='category',
            field=models.CharField(default='Languages', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='keywords',
            field=models.CharField(default='Javascript', max_length=255),
        ),
    ]
