# Generated by Django 5.0.4 on 2024-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_professionalregistration_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalregistration',
            name='completion_date',
            field=models.DateField(),
        ),
    ]
