# Generated by Django 5.0.4 on 2024-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_professionalregistration_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalregistration',
            name='completion_date',
        ),
    ]
