# Generated by Django 5.0.4 on 2024-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_professionalregistration_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalregistration',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professionalregistration',
            name='keywords',
            field=models.TextField(),
        ),
    ]
