# Generated by Django 5.0.4 on 2024-04-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_degree_name_professionalregistration_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalregistration',
            old_name='company_name',
            new_name='institution_name',
        ),
    ]
