# Generated by Django 5.0.4 on 2024-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_company_name_professionalregistration_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalregistration',
            name='degree_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='month_complete',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='year_complete',
            field=models.IntegerField(default=2000),
        ),
    ]
