# Generated by Django 5.0.4 on 2024-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_professionalregistration_degree_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalregistration',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professionalregistration',
            name='keywords',
            field=models.CharField(default='', max_length=255),
        ),
    ]
