# Generated by Django 5.0.4 on 2024-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_professionalregistration_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='professional',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='keywords',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='user_name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='degree_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='professional',
            name='month_complete',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='professional',
            name='year_complete',
            field=models.IntegerField(default=2000),
        ),
    ]
