# Generated by Django 5.0.4 on 2024-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_email_address_professional_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofiledeleterequest',
            old_name='request_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='employerprofiledeleterequest',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employerprofiledeleterequest',
            name='zip',
            field=models.CharField(default='', max_length=10),
        ),
    ]
